version: '2'
services:
  web:
    build:
      context: .
      dockerfile: devel.dockerfile
    volumes:
      - "./src/apof/:/opt/apof/src/apof"
      - "./media:/opt/apof/media"
      - "./fron/dist:/opt/apof/statics"
      - "./statics-assets:/opt/apof/static-assets/"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=apof.service.settings.development
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=apof
    command: mysqld --character-set-server=utf8
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "./media:/var/media"
      - "./statics-assets:/opt/apof/statics-assets/"
    depends_on:
      - web
  fron:
    build:
      context: fron
      dockerfile: devel.dockerfile
    volumes:
      - "./fron/src/:/opt/apof/fron/src"
      - "./fron/dist:/opt/apof/fron/dist"
      - "./fron/bower.json:/opt/apof/fron/bower.json"
      - "./fron/gulpfile.js:/opt/apof/fron/src/gulpfile.js"
      - "./fron/package.json:/opt/apof/fron/src/package.json"
